server:
  port: ${PORT:8004}

spring:
  application:
    name: ms-profile
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/PsicoDB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: asapsitterapp@gmail.com
    password: uree ixye wmai umra
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

