server:
  port: ${PORT:8004}

spring:
  application:
    name: ms-profile
  datasource:
    type: org.postgresql.ds.PGSimpleDataSource  # Cambio aquí para usar el driver correcto
    username: ${POSTGRES_USERNAME:psicodb_user}
    password: ${POSTGRES_PASSWORD:tbhzqj4uykYY6CSOkmcmhxiKFjjBJ6pY}
    url: ${POSTGRES_URL:jdbc:postgresql://dpg-cpeb55dds78s73etol00-a.oregon-postgres.render.com:5432/psicodb}  # Corrección aquí para usar el formato adecuado
    driver-class-name: org.postgresql.Driver  # Asegurándonos de especificar el driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: asapsitterapp@gmail.com
    password: ureeixyewmaiumra
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

chatgpt:
  url: https://openrouter.ai/api/v1/chat/completions
  apikey: ${api_key}