server:
  port: ${PORT:8004}

spring:
  application:
    name: ms-profile
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:jose}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/PsicoDB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: asapsitterapp@gmail.com
    password: ureeixyewmaiumra
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

chatgpt:
  url: https://openrouter.ai/api/v1/chat/completions
  apikey: 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
